### ISSUE TITLE
Add Fade between Tab Select

### ISSUE THREAD

**Issue by chance-nelson** [PathLabs/primacy_demo#22]
It may be a good idea to add a fade in/out in CSS for tab selection, as of right now it's just a snap to black, then to the next tab.

@skate54345, is this doable?

**Comment by skate54345** [comment]
This might be possible but probably isn't worth the trouble for the demo.  Tab traversal will likely be changed in the final product and we are going to have a loading screen/progress bar in between at that stage.  

I'm hoping to add some other things once the input validation stuff is hooked up though.  I need to add a text box with the current number that corresponds with the slider on tab 2
