### ISSUE TITLE
BUG: FASTA file uploader doesn't display selected file name

### ISSUE THREAD

**Issue by turanoo** [PathLabs/primacy_demo#78]
**Describe the bug**
 FASTA file uploader does not show what file is selected.

**To Reproduce**
1. Select a File to Bulk Upload

**Expected behavior**
Should show the name of the file uploaded and change when the file upload is changed.

**Comment by chance-nelson** [comment]
This is because keeping the previous file in the input's state would make it impossible for a user to re upload the same file (ex. user bulk uploads file, then accidentally deletes a target sequence)
